import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from "recharts";
import "./styles.css";

const API="/api";
const money=n=>new Intl.NumberFormat("vi-VN",{style:"currency",currency:"VND",maximumFractionDigits:0}).format(Number(n)||0);
const today=()=>new Date().toISOString().slice(0,10);
const methods=["Tiền mặt","Chuyển khoản","Home","Việt Tín","POS","MPOS 12TH","MPOS 18TH","MPOS 24TH","HD"];
const sources=["FB","FBN","VL","PR","CV","UP","NN","DD"];
const blankSale={date:today(),customer_name:"",source:"FB",branch:"",package:"",total_amount:0,paid_amount:0,payment_method:"Tiền mặt",consultant:"",status:"Đã đăng ký",note:""};
const blankLead={date:today(),name:"",phone:"",contact_status:"Mới",booking_date:"",branch:"",trainer:"",result:"",after_appointment:""};

async function api(path,opts={}){
 const token=localStorage.getItem("crm_token");
 const r=await fetch(API+path,{...opts,headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{}),...(opts.headers||{})}});
 const text=await r.text();
 let data={};
 try{data=text?JSON.parse(text):{}}catch{data={error:"Máy chủ trả về dữ liệu không hợp lệ"}}
 if(r.status===401){
   localStorage.removeItem("crm_token");
   localStorage.removeItem("crm_user");
   window.dispatchEvent(new Event("crm_auth_expired"));
 }
 if(!r.ok)throw Error(data.error||`Lỗi máy chủ (${r.status})`);
 return data;
}
class ErrorBoundary extends React.Component{
 constructor(props){super(props);this.state={error:null}}
 static getDerivedStateFromError(error){return {error}}
 componentDidCatch(error,info){console.error("CRM render error:",error,info)}
 render(){
   if(this.state.error)return <div className="app-error"><h2>CRM gặp lỗi hiển thị</h2><p>Phiên làm việc hoặc dữ liệu vừa tải có vấn đề. Hãy bấm nút bên dưới để đăng nhập lại.</p><button className="primary" onClick={()=>{localStorage.removeItem("crm_token");localStorage.removeItem("crm_user");location.reload()}}>Đăng nhập lại</button></div>;
   return this.props.children;
 }
}
function App(){
 const [user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem("crm_user")||"null")}catch{return null}});
 const [login,setLogin]=useState({username:"admin",password:"kpmf0209@admin"});
 useEffect(()=>{
   const onExpired=()=>setUser(null);
   window.addEventListener("crm_auth_expired",onExpired);
   return ()=>window.removeEventListener("crm_auth_expired",onExpired);
 },[]);
 if(!user)return <Login login={login} setLogin={setLogin} onLogin={u=>setUser(u)}/>;
 return <ErrorBoundary><Shell user={user} logout={()=>{localStorage.removeItem("crm_token");localStorage.removeItem("crm_user");setUser(null)}}/></ErrorBoundary>;
}
function Login({login,setLogin,onLogin}){
 const [err,setErr]=useState("");
 const submit=async e=>{e.preventDefault();try{const x=await api("/login",{method:"POST",body:JSON.stringify(login)});localStorage.setItem("crm_token",x.token);localStorage.setItem("crm_user",JSON.stringify(x.user));onLogin(x.user)}catch(e){setErr(e.message)}};
 return <div className="login"><form onSubmit={submit} className="login-card"><div className="brand">CRM<span>PRO</span></div><h1>Đăng nhập</h1><p>Hệ thống quản lý doanh số nội bộ</p><label>Tên tài khoản<input value={login.username} onChange={e=>setLogin({...login,username:e.target.value})}/></label><label>Mật khẩu<input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label>{err&&<div className="error">{err}</div>}<button className="primary">Đăng nhập</button><small>Demo mặc định: admin / kpmf0209@admin</small></form></div>
}
function Shell({user,logout}){
 const [page,setPage]=useState("dashboard"),[open,setOpen]=useState(false);
 const items=[["dashboard","Dashboard","▦"],["sales","Doanh số","₫"],["leads","Data nhận","☷"],["funnel","Funnel","◉"],["weekly","Doanh số tuần","↗"],["sources","Hợp đồng theo nguồn","◎"],["checkins","Check-in","✓"],["bonuses","Bonus","★"],["holds","Bảo lưu","◷"],["targets","Target Tổng","🎯"]];
 return <div className="app"><aside className={open?"open":""}><div className="logo">CRM<span>PRO</span></div><button className="mobile-close" onClick={()=>setOpen(false)}>×</button><nav>{items.map(x=><button key={x[0]} className={page===x[0]?"active":""} onClick={()=>{setPage(x[0]);setOpen(false)}}><b>{x[2]}</b>{x[1]}</button>)}</nav><div className="side-bottom"><div>⚙ Cài đặt</div><div className="muted">v1.0 • Internal</div></div></aside><main><header><button className="hamb" onClick={()=>setOpen(true)}>☰</button><div><strong>{items.find(x=>x[0]===page)?.[1]}</strong><span className="crumb"> / CRMPRO</span></div><div className="user-menu"><span>👤 {user.name} · {user.role}</span><button onClick={logout}>Đăng xuất</button></div></header><section className="content">{page==="dashboard"?<Dashboard/>:page==="sales"?<Sales user={user}/>:page==="leads"?<Leads user={user}/>:page==="funnel"?<Funnel/>:page==="weekly"?<Weekly/>:page==="sources"?<Sources/>:page==="checkins"?<Checkins/>:page==="bonuses"?<Bonuses user={user}/>:page==="holds"?<Holds user={user}/>:<Targets/>}</section></main></div>
}
function Dashboard(){
 const [d,setD]=useState(null);useEffect(()=>{api("/dashboard").then(setD)},[]);
 if(!d)return <Loading/>;
 const cards=[["Doanh số hôm nay",money(d.todaySales),"↗"],["Doanh số tháng",money(d.monthSales),"₫"],["Thực nhận",money(d.netReceived),"✓"],["Data nhận",d.leads,"☷"],["Đã book",d.booked,"▣"],["Đã ghé",d.visited,"◉"],["Đăng ký",d.registered,"✓"],["Hoàn thành target",`${(d.completion*100).toFixed(1)}%`,"🎯"]];
 return <><div className="page-title"><div><h1>Dashboard tổng quan</h1><p>Doanh số, funnel và hiệu suất trong tháng hiện tại.</p></div></div><div className="cards">{cards.map(c=><div className="card" key={c[0]}><div className="icon">{c[2]}</div><span>{c[0]}</span><strong>{c[1]}</strong></div>)}</div><div className="grid2"><div className="panel chart"><h3>Doanh số theo tuần</h3><div className="chartbox"><ResponsiveContainer width="100%" height="100%"><BarChart data={d.weekly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="week"/><YAxis tickFormatter={v=>`${Math.round(v/1000000)}M`}/><Tooltip formatter={v=>money(v)}/><Bar dataKey="sales" name="Doanh số" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="panel"><h3>Funnel tháng</h3><div className="funnel"><div><span>Data nhận</span><b>{d.leads}</b></div><div><span>Book hẹn</span><b>{d.booked}</b></div><div><span>Đã ghé</span><b>{d.visited}</b></div><div><span>Đăng ký</span><b>{d.registered}</b></div></div><div className="rates"><span>Book/Data: <b>{d.leads?(d.booked/d.leads*100).toFixed(1):0}%</b></span><span>Ghé/Book: <b>{d.booked?(d.visited/d.booked*100).toFixed(1):0}%</b></span><span>ĐK/Ghé: <b>{d.visited?(d.registered/d.visited*100).toFixed(1):0}%</b></span></div></div></div></>
}
function Loading(){return <div className="loading">Đang tải dữ liệu...</div>}
function Toolbar({onAdd,search="",setSearch=()=>{},children}){return <div className="toolbar"><input placeholder="🔎 Tìm kiếm..." value={search||""} onChange={e=>setSearch(e.target.value)}/>{children}<button className="primary" onClick={onAdd}>＋ Thêm mới</button></div>}
function Modal({title,onClose,children}){return <div className="modal-bg"><div className="modal"><div className="modal-head"><h3>{title}</h3><button onClick={onClose}>×</button></div>{children}</div></div>}
function Sales({user}){
 const [rows,setRows]=useState([]),[q,setQ]=useState(""),[edit,setEdit]=useState(null);
 const load=()=>api("/sales").then(setRows);useEffect(load,[]);
 const filtered=useMemo(()=>rows.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const save=async x=>{try{if(x.id)await api("/sales/"+x.id,{method:"PUT",body:JSON.stringify(x)});else await api("/sales",{method:"POST",body:JSON.stringify(x)});setEdit(null);load()}catch(e){alert(e.message)}};
 const del=async id=>{if(confirm("Xóa dữ liệu này?")){await api("/sales/"+id,{method:"DELETE"});load()}};
 return <><PageTitle title="Doanh số theo ngày" desc="Nhập và chỉnh sửa trực tiếp dữ liệu bán hàng."/><Toolbar onAdd={()=>setEdit({...blankSale})} search={q} setSearch={setQ}><select onChange={e=>setQ(e.target.value)}><option value="">Tất cả nguồn</option>{sources.map(s=><option>{s}</option>)}</select></Toolbar><div className="table-wrap"><table><thead><tr>{["Ngày","Họ tên","Nguồn","Chi nhánh","Gói tập","Đã TT","HTTT","Phí","Sau phí","Sau thuế","Thực nhận","Tình trạng","Tư vấn",""].map(h=><th>{h}</th>)}</tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{x.date}</td><td><b>{x.customer_name}</b></td><td>{x.source}</td><td>{x.branch}</td><td>{x.package}</td><td>{money(x.paid_amount)}</td><td>{x.payment_method}</td><td>{(x.fee_rate*100).toFixed(0)}%</td><td>{money(x.after_fee)}</td><td>{money(x.after_tax)}</td><td><b>{money(x.net_received)}</b></td><td><span className="tag">{x.status}</span></td><td>{x.consultant}</td><td className="actions"><button onClick={()=>setEdit(x)}>Sửa</button>{user.role==="Admin"&&<button className="danger" onClick={()=>del(x.id)}>Xóa</button>}</td></tr>)}</tbody></table></div>{edit&&<SaleForm value={edit} onClose={()=>setEdit(null)} onSave={save}/>}</>
}
function SaleForm({value,onClose,onSave}){const [x,setX]=useState(value);const set=(k,v)=>setX({...x,[k]:v});return <Modal title={x.id?"Sửa doanh số":"Thêm khách hàng"} onClose={onClose}><div className="formgrid">{[["date","Ngày","date"],["customer_name","Họ tên","text"],["source","Nguồn","text"],["branch","Chi nhánh","text"],["package","Gói tập","text"],["total_amount","Tổng tiền","number"],["paid_amount","Đã thanh toán","number"],["consultant","Người tư vấn","text"],["status","Tình trạng","text"]].map(([k,l,t])=><label>{l}<input type={t} value={x[k]??""} onChange={e=>set(k,t==="number"?Number(e.target.value):e.target.value)}/></label>)}<label>HTTT<select value={x.payment_method} onChange={e=>set("payment_method",e.target.value)}>{methods.map(m=><option>{m}</option>)}</select></label><label>Ghi chú<input value={x.note||""} onChange={e=>set("note",e.target.value)}/></label></div><div className="calc-preview">Hệ thống tự tính phí, doanh số sau phí, thuế và thực nhận theo HTTT.</div><div className="modal-actions"><button onClick={onClose}>Hủy</button><button className="primary" onClick={()=>onSave(x)}>Lưu</button></div></Modal>}
function PageTitle({title,desc}){return <div className="page-title"><div><h1>{title}</h1><p>{desc}</p></div></div>}
function Leads({user}){const [rows,setRows]=useState([]),[q,setQ]=useState(""),[edit,setEdit]=useState(null);const load=()=>api("/leads").then(setRows);useEffect(load,[]);const filtered=rows.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q.toLowerCase()));const save=async x=>{await api(x.id?"/leads/"+x.id:"/leads",{method:x.id?"PUT":"POST",body:JSON.stringify(x)});setEdit(null);load()};return <><PageTitle title="Data nhận theo ngày" desc="Cập nhật trạng thái lead trực tiếp."/><Toolbar onAdd={()=>setEdit({...blankLead})} search={q} setSearch={setQ}/><div className="table-wrap"><table><thead><tr>{["Ngày","Họ tên","SĐT","Liên hệ","Lịch book","Chi nhánh","HLV follow","Kết quả","Sau hẹn",""].map(h=><th>{h}</th>)}</tr></thead><tbody>{filtered.map(x=><tr><td>{x.date}</td><td>{x.name}</td><td>{x.phone}</td><td><span className="tag">{x.contact_status}</span></td><td>{x.booking_date||"-"}</td><td>{x.branch}</td><td>{x.trainer}</td><td>{x.result}</td><td>{x.after_appointment}</td><td><button onClick={()=>setEdit(x)}>Sửa</button></td></tr>)}</tbody></table></div>{edit&&<Modal title={edit.id?"Sửa lead":"Thêm lead"} onClose={()=>setEdit(null)}><div className="formgrid">{[["date","Ngày","date"],["name","Họ tên","text"],["phone","SĐT","tel"],["booking_date","Lịch book","date"],["branch","Chi nhánh","text"],["trainer","HLV follow","text"],["result","Kết quả","text"],["after_appointment","Kết quả sau hẹn","text"]].map(([k,l,t])=><label>{l}<input type={t} value={edit[k]||""} onChange={e=>setEdit({...edit,[k]:e.target.value})}/></label>)}<label>Tình trạng liên hệ<select value={edit.contact_status} onChange={e=>setEdit({...edit,contact_status:e.target.value})}>{["Mới","Đang liên hệ","Đã book","Không nghe máy","Không quan tâm"].map(x=><option>{x}</option>)}</select></label></div><div className="modal-actions"><button onClick={()=>setEdit(null)}>Hủy</button><button className="primary" onClick={()=>save(edit)}>Lưu</button></div></Modal>}</>}
function Funnel(){const [rows,setRows]=useState([]);useEffect(()=>api("/leads").then(setRows),[]);const sales=useMemo(()=>rows,[rows]);const stats=[["Tổng data",sales.length],["Book hẹn",sales.filter(x=>x.booking_date).length],["Đã ghé",sales.filter(x=>["Đã ghé","Visited","Ghé"].includes(x.result)).length]];return <><PageTitle title="Data khách hàng / Funnel" desc="Theo dõi Data → Book → Ghé → Đăng ký."/><div className="funnel-cards">{stats.map(x=><div className="bigstat"><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><div className="panel"><h3>Tỷ lệ chuyển đổi</h3><div className="conversion"><Metric name="Book / Data" value={stats[0][1]?stats[1][1]/stats[0][1]:0}/><Metric name="Ghé / Book" value={stats[1][1]?stats[2][1]/stats[1][1]:0}/></div><p className="muted">Dữ liệu được nhóm theo tuần dựa trên ngày nhận lead.</p></div></>}
function Metric({name,value}){return <div><span>{name}</span><strong>{(value*100).toFixed(1)}%</strong><div className="progress"><i style={{width:`${Math.min(100,value*100)}%`}}/></div></div>}
function Weekly(){const [sales,setSales]=useState([]);useEffect(()=>api("/sales").then(setSales),[]);const weeks=[1,2,3,4,5].map(w=>{const r=sales.filter(x=>Math.floor((Number(x.date.slice(8,10))-1)/7)+1===w);return {w,total:r.reduce((a,b)=>a+b.paid_amount,0),net:r.reduce((a,b)=>a+b.net_received,0)}});return <><PageTitle title="Doanh số theo tuần" desc="Tự động chia tuần 1–5 theo ngày trong tháng."/><div className="panel"><table><thead><tr><th>Tuần</th><th>Tổng doanh số</th><th>Thực nhận</th><th>Số hợp đồng</th></tr></thead><tbody>{weeks.map(w=><tr><td><b>Tuần {w.w}</b></td><td>{money(w.total)}</td><td>{money(w.net)}</td><td>{sales.filter(x=>Math.floor((Number(x.date.slice(8,10))-1)/7)+1===w.w).length}</td></tr>)}</tbody></table></div></>}
function Sources(){const [sales,setSales]=useState([]);useEffect(()=>api("/sales").then(setSales),[]);return <><PageTitle title="Hợp đồng theo nguồn" desc="Tổng hợp số hợp đồng và doanh số theo nguồn."/><div className="source-grid">{sources.map(s=>{const r=sales.filter(x=>x.source===s);const people=[...new Set(r.map(x=>x.consultant).filter(Boolean))];const count=r.reduce((a,x)=>a+(people.length>1?0.5:1),0);return <div className="source-card"><b>{s}</b><span>{r.length} hợp đồng</span><strong>{money(r.reduce((a,x)=>a+x.paid_amount,0))}</strong><small>Quy đổi: {count}</small></div>})}</div></>}
function Checkins(){const [rows,setRows]=useState([]),[filter,setFilter]=useState("Tất cả");const load=()=>api("/checkins").then(setRows);useEffect(load,[]);const setStatus=async(id,status)=>{await api("/checkins/"+id,{method:"PUT",body:JSON.stringify({status})});load()};const shown=rows.filter(x=>filter==="Tất cả"||x.status===filter);return <><PageTitle title="Check-in khách hàng" desc="Tự động lấy khách từ dữ liệu doanh số."/><div className="filter-pills">{["Tất cả","Đang tập","Chưa check-in","Đã check-in","Hết hạn","Bảo lưu"].map(x=><button className={filter===x?"selected":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="table-wrap"><table><thead><tr><th>Khách hàng</th><th>Gói tập</th><th>Chi nhánh</th><th>Tư vấn</th><th>Ngày đăng ký</th><th>Ngày hết hạn</th><th>Trạng thái</th><th>Check-in</th></tr></thead><tbody>{shown.map(x=><tr><td>{x.customer_name}</td><td>{x.package}</td><td>{x.branch}</td><td>{x.consultant}</td><td>{x.date}</td><td>{x.expiry}</td><td>{x.status}</td><td><select value={x.status} onChange={e=>setStatus(x.id,e.target.value)}><option>Chưa check-in</option><option>Đã check-in</option><option>Đang tập</option><option>Hết hạn</option><option>Bảo lưu</option></select></td></tr>)}</tbody></table></div></>}
function Bonuses({user}){const [rows,setRows]=useState([]),[edit,setEdit]=useState(null);const load=()=>api("/bonuses").then(setRows);useEffect(load,[]);const save=async x=>{await api(x.id?"/bonuses/"+x.id:"/bonuses",{method:x.id?"PUT":"POST",body:JSON.stringify(x)});setEdit(null);load()};const del=async id=>{if(confirm("Xóa bonus?")){await api("/bonuses/"+id,{method:"DELETE"});load()}};return <><PageTitle title="Bonus" desc="Quản lý các khoản bonus."/><Toolbar onAdd={()=>setEdit({date:today(),bonus:"",amount:0})}/><div className="panel"><table><thead><tr><th>Ngày tháng</th><th>Bonus</th><th>Số tiền</th><th></th></tr></thead><tbody>{rows.map(x=><tr><td>{x.date}</td><td>{x.bonus}</td><td>{money(x.amount)}</td><td><button onClick={()=>setEdit(x)}>Sửa</button>{user.role==="Admin"&&<button className="danger" onClick={()=>del(x.id)}>Xóa</button>}</td></tr>)}</tbody></table></div>{edit&&<Modal title="Bonus" onClose={()=>setEdit(null)}><div className="formgrid"><label>Ngày<input type="date" value={edit.date} onChange={e=>setEdit({...edit,date:e.target.value})}/></label><label>Bonus<input value={edit.bonus} onChange={e=>setEdit({...edit,bonus:e.target.value})}/></label><label>Số tiền<input type="number" value={edit.amount} onChange={e=>setEdit({...edit,amount:Number(e.target.value)})}/></label></div><div className="modal-actions"><button onClick={()=>setEdit(null)}>Hủy</button><button className="primary" onClick={()=>save(edit)}>Lưu</button></div></Modal>}</>}
function Holds({user}){const [rows,setRows]=useState([]);const load=()=>api("/holds").then(setRows);useEffect(load,[]);const update=async(x)=>{await api("/holds/"+x.id,{method:"PUT",body:JSON.stringify({months:x.months,status:x.status})});load()};return <><PageTitle title="Bảo lưu" desc="Quản lý danh sách khách đang bảo lưu."/><div className="panel"><table><thead><tr><th>Khách hàng</th><th>Gói tập</th><th>Chi nhánh</th><th>Tư vấn</th><th>Ngày đăng ký</th><th>Số tháng</th><th>Trạng thái</th><th></th></tr></thead><tbody>{rows.map(x=><tr><td>{x.customer_name}</td><td>{x.package}</td><td>{x.branch}</td><td>{x.consultant}</td><td>{x.date}</td><td><input className="small-input" type="number" value={x.months} onChange={e=>setRows(rows.map(r=>r.id===x.id?{...r,months:Number(e.target.value)}:r))}/></td><td><select value={x.status} onChange={e=>setRows(rows.map(r=>r.id===x.id?{...r,status:e.target.value}:r))}><option>Đang bảo lưu</option><option>Đã kết thúc</option></select></td><td><button onClick={()=>update(x)}>Lưu</button></td></tr>)}</tbody></table></div></>}
function Targets(){const [rows,setRows]=useState([]),[x,setX]=useState({period_type:"month",period:new Date().toISOString().slice(0,7),target:0});const load=()=>api("/targets").then(setRows);useEffect(load,[]);const save=async()=>{await api("/targets",{method:"POST",body:JSON.stringify(x)});load()};return <><PageTitle title="Target Tổng" desc="Quản lý target theo tháng → tuần → ngày."/><div className="panel target-form"><select value={x.period_type} onChange={e=>setX({...x,period_type:e.target.value})}><option value="month">Tháng</option><option value="week">Tuần</option><option value="day">Ngày</option></select><input value={x.period} onChange={e=>setX({...x,period:e.target.value})}/><input type="number" placeholder="Target" value={x.target} onChange={e=>setX({...x,target:Number(e.target.value)})}/><button className="primary" onClick={save}>Lưu target</button></div><div className="panel"><table><thead><tr><th>Thời gian</th><th>Loại</th><th>Target</th></tr></thead><tbody>{rows.map(r=><tr><td>{r.period}</td><td>{r.period_type}</td><td>{money(r.target)}</td></tr>)}</tbody></table></div></>}
createRoot(document.getElementById("root")).render(<ErrorBoundary><App/></ErrorBoundary>);